{theme}

set nu rnu

set scrolloff=7

filetype plugin on

set autoindent
set smartindent

set tabstop=4
set shiftwidth=4
" set expandtab " converts tabs into spaces

set incsearch

set wildmenu

" For easy movement in file

map [1;5D b
map [1;5C e
map [1;5A <C-Up>
map [1;5B <C-Down>
map! [1;5D <C-Left>
map! [1;5C <C-Right>
map! [1;5A <C-Up>
map! [1;5B <C-Down>

noremap <silent> J 10j
noremap <silent> K 10k

" map  :so ~/.vimrc

" https://stackoverflow.com/a/9550944
au BufNewFile,BufRead *.rasi set filetype=css
au BufRead,BufNewFile *.g set filetype=antlr3
au BufRead,BufNewFile *.g4 set filetype=antlr4

syntax on
au BufRead,BufNewFile *.g4 set filetype=antlr4
