[global/wm]

include-file = ~/.config/polybar/colors.ini
#include-file = ~/.config/polybar/cfg.ini

[bar/mine]

background = ${color.bg}
foreground = ${color.fg}

font-0 = "Ubuntu Condensed:size=13;2"

modules-center = date
modules-left = workspaces
modules-right = cpu sep memory sep battery sep net

[module/sep]
type = custom/text
content = |

content-padding = 2

content-background = ${color.bg}
content-foreground = ${color.brd}

[module/workspaces]
type = internal/xworkspaces

pin-workspaces = true

enable-click = false

enable-scroll = false

#icon-0 = ♚
#icon-1 = ♛
#icon-2 = ♜
#icon-3 = ♝
#icon-4 = ♞
icon-default = ●

format = <label-state>

label-monitor = %name%

label-active = %icon%
label-active-foreground = ${color.fg}
label-active-background = ${color.brd}
label-active-underline = #FF0000
label-active-padding = 2

label-occupied = %icon%
label-occupied-foreground = ${color.txt}
label-occupied-background = ${color.brd}
label-occupied-padding = 2

label-urgent = %icon%
label-urgent-foreground = ${color.txt}
label-urgent-background = ${color.bga}
label-urgent-padding = 2

[module/memory]
type = internal/memory
interval = 2

format = <label>
label = %mb_used%

format-prefix = "RAM: "

format-foreground = ${color.fg}

[module/cpu]
type = internal/cpu
interval = 2

format-prefix = "CPU: "

format-foreground = ${color.fg}

[module/date]
type = internal/date

interval = 1.0

time = %d-%m-%Y %H:%M

format = <label>
label = %time%

[module/battery]
type = internal/battery

battery = BAT0
adapter = ADP1

full-at = 99

poll-interval = 2

format-charging = <label-charging>
format-discharging = <label-discharging>

label-charging = BAT: %percentage%%
label-discharging = BAT: %percentage%%

[module/net]
type = internal/network
;; ip link to know the interface
interface = wlp3s0

interval = 3.0

; All labels support the following tokens:
; ;   %ifname%    [wireless+wired]
; ;   %local_ip%  [wireless+wired]
; ;   %local_ip6% [wireless+wired]
; ;   %essid%     [wireless]
; ;   %signal%    [wireless]
; ;   %upspeed%   [wireless+wired]
; ;   %downspeed% [wireless+wired]
; ;   %linkspeed% [wired]

label-connected = NET: ↑%upspeed%  ↓%downspeed%
format-connected = <label-connected>

label-disconnected = X
format-disconnected = <label-disconnected>
